#	 _____ _     _             _
#	|_   _| |__ (_)_ __   __ _/ |
#	  | | | '_ \| | '_ \ / _` | |
#	  | | | | | | | | | | (_| | |
#	  |_| |_| |_|_|_| |_|\__, |_|
#	                     |___/
#	This first example inserts a thing into the store.
#	URI: 										<http://MyFirstWebThing.com>
#	Name: 										'Thing1'
#	Thing-Description URI: 						<http://MyFirstWebThingDescription.com>
#	Number of Actions: 							2
#	Number of Events: 							1
#	Number of Properties: 						1
#	Action 1 URI: 								<http://MyFirstWebThing.com/Action1>
#	Action 1 Name: 								'Thing1_Action1'
#	Action 1 InputDataSchema FieldSchema: 		blank node --> xsd:string
#	Action 1 OutputDataSchema FieldSchema: 		blank node --> ResourceURI
#	Action 2 URI: 								<http://MyFirstWebThing.com/Action2>
#	Action 2 Name: 								'Thing1_Action2'
#	Action 2 OutputDataSchema FieldSchema: 		blank node --> xsd:integer
#	Event URI: 									<http://MyFirstWebThing.com/Event1>
#	Event Name: 								'Thing1_Event1'
# 	Event OutputDataSchema FieldSchema: 		blank node --> xsd:dateTimeStamp
#	Property URI: 								<http://MyFirstWebThing.com/Property1>
#	Property Name: 								'Thing1_Property1'
#	Property Stability: 						'1000'
#	Property Writability: 						'true'
#	Property forProperty:						<http://MyFirstWebThing.com/Action2>
#	Property PropertyDataSchema FieldSchema: 	blank node --> xsd:string
#	Property PropertyData:						<http://MyFirstWebThing.com/Property1/PropertyData>
#	Property initial value: 					'Hello World!'


prefix swot: <http://wot.arces.unibo.it/ontology/web_of_things#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA {
	# BASIC INFORMATION
  <http://MyFirstWebThing.com> 	rdf:type swot:Thing;
								swot:hasName 'Thing1';
								swot:hasThingDescription <http://MyFirstWebThingDescription.com>.
  <http://MyFirstWebThingDescription.com> 	rdf:type swot:ThingDescription;
											swot:hasInteractionPattern 	<http://MyFirstWebThing.com/Action1>, 
																	<http://MyFirstWebThing.com/Action2>, 
																	<http://MyFirstWebThing.com/Event1>, 
																	<http://MyFirstWebThing.com/Property1>;
											swot:hasAction <http://MyFirstWebThing.com/Action1>, <http://MyFirstWebThing.com/Action2>;
											swot:hasEvent <http://MyFirstWebThing.com/Event1>;
											swot:hasProperty <http://MyFirstWebThing.com/Property1>.
	
	# ACTION 1 TRIPLES
  <http://MyFirstWebThing.com/Action1> 	rdf:type swot:InteractionPattern, swot:Action;
										swot:hasName 'Thing1_Action1';
										swot:hasDataSchema <http://XSDstringDataSchema.org>, <http://GenericWebResourceDataSchema.org>;
										swot:hasInputDataSchema <http://XSDstringDataSchema.org>;
										swot:hasOutputDataSchema <http://GenericWebResourceDataSchema.org>.
	
	# ACTION 2 TRIPLES
  <http://MyFirstWebThing.com/Action2> 	rdf:type swot:InteractionPattern, swot:Action;
										swot:hasName 'Thing1_Action2';
										swot:hasDataSchema <http://XSDintegerDataSchema.org>;
										swot:hasOutputDataSchema <http://XSDintegerDataSchema.org>.
  
	# EVENT TRIPLES
  <http://MyFirstWebThing.com/Event1> 	rdf:type swot:InteractionPattern, swot:Event;
										swot:hasName 'Thing1_Event1';
										swot:hasDataSchema <http://XSDdateTimeStampDataSchema.org>;
										swot:hasOutputDataSchema <http://XSDdateTimeStampDataSchema.org>.
  
	# PROPERTY TRIPLES
  <http://MyFirstWebThing.com/Property1> 	rdf:type swot:InteractionPattern, swot:Property;
											swot:hasName 'Thing1_Property1';
											swot:hasStability '1000';
											swot:isWritable 'true';
											swot:hasDataSchema <http://XSDstringDataSchema.org>;
											swot:hasPropertyDataSchema <http://XSDstringDataSchema.org>;
											swot:hasData <http://MyFirstWebThing.com/Property1/PropertyData>;
											swot:hasPropertyData <http://MyFirstWebThing.com/Property1/PropertyData>.
  <http://MyFirstWebThing.com/Property1/PropertyData> rdf:type swot:PropertyData, swot:Data;
													  swot:hasValue 'Hello World!'.
  <http://MyFirstWebThing.com/Action2> swot:forProperty <http://MyFirstWebThing.com/Property1>.									
  }