#                                                    _      _   _                 _
#     _ __   _____      __  ___ ___  _ __ ___  _ __ | | ___| |_(_) ___  _ __     | |_ ___ 
#    | '_ \ / _ \ \ /\ / / / __/ _ \| '_ ` _ \| '_ \| |/ _ \ __| |/ _ \| '_ \    | __/ __| 
#    | | | |  __/\ V  V / | (_| (_) | | | | | | |_) | |  __/ |_| | (_) | | | |   | |_\__ \ 
#    |_| |_|\___| \_/\_/___\___\___/|_| |_| |_| .__/|_|\___|\__|_|\___/|_| |_|____\__|___/
#                     |_____|                 |_|                           |_____|
#    

ADD_COMPLETION_TIMESTAMP:
    sparql: "
        insert {?aInstance swot:hasCompletionTimeStamp ?ts}
        where {
            ?aInstance rdf:type swot:ActionInstance.
            bind (now() as ?ts)
        }"
    forcedBindings:
        aInstance:
            type: uri
            value: ""
