#         _      _    _   _     _             
#      __| | ___| |  | |_| |__ (_)_ __   __ _ 
#     / _` |/ _ \ |  | __| '_ \| | '_ \ / _` |
#    | (_| |  __/ |  | |_| | | | | | | | (_| |
#     \__,_|\___|_|___\__|_| |_|_|_| |_|\__, |
#                |_____|                |___/ 
#    
#   Deletes thing, subthing relationships and thing descriptor with
#   interaction pattern relationships.
#   Subthing and interaction pattern are left.

DELETE_THING:
    sparql: "
        delete {
            ?ds_uri rdf:type swot:DataSchema;
                    swot:hasFieldSchema ?fs_uri.
            ?fs_uri rdf:type ?fs_types.
        } where {
            ?ds_uri rdf:type swot:DataSchema;
                    swot:hasFieldSchema ?fs_uri.
            ?fs_uri rdf:type ?fs_types.
		}"
    forcedBindings:
        ds_uri:
            type: uri
            value: ""
        fs_uri:
            type: uri
            value: ""
